motor_num: 20        # 电机数量
actions_size: 20     # action的大小
dt: 0.0025  # 控制频率周期
xsense_data_roll_offset: 0.0
zero_pos_offset: [
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
    ]
ct_scale: [
          2.1, 2.1, 3.207, 2.673, 2.6, 2.6, 
          2.1, 2.1, 3.207, 2.673, 2.6, 2.6, 
          3.207, 3.207, 3.207, #TODO:待更新 pry
          3.207, 2.28, 5.89, 5.89, 3.35, 2.3, 2.3, 
          3.207, 2.28, 5.89, 5.89, 3.35, 2.3, 2.3
    ]


joint_kp_p: 
  [
    700.0, 700.0, 500.0, 700.0, 15.0, 15.0, #left leg
    700.0, 700.0, 500.0, 700.0, 15.0, 15.0,
    60.0, 20.0, 10.0, 10.0, # left arm
    60.0, 20.0, 10.0, 10.0,
  ]
joint_kd_p: 
  [
    20.0, 20.0, 15.0, 10.0, 1.25, 1.25, 
    20.0, 20.0, 15.0, 10.0, 1.25, 1.25,
    3.0, 1.5, 1.0, 1.0,
    3.0, 1.5, 1.0, 1.0
  ]


joystick:
  forward_command_offset: 0.0
  lateral_command_offset: 0.0
  rotation_command_offset: 0.0

simulation: false # 是否在仿真环境下运行
mlp:
  path: "/config/policy/policy1107"