motor_num: 30         # 电机数量 (Number of motors: 20 for Tienkung Lite, 30 for Tienkung Pro)
actions_size: 30      # action的大小 (Action size: 20 for Tienkung Lite, 30 for Tienkung Pro)
dt: 0.0025            # 控制频率周期 (Control frequency period) (1/0.0025 = 400Hz)
xsense_data_roll_offset: 0.0

# Tienkung Lite
# zero_pos_offset: [
#       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
#       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
#       0.0, 0.0, 0.0,
#       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
#       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
#     ]

# Tienkung Pro
zero_pos_offset: [
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0,              # left leg:  "l_hip_roll", "l_hip_pitch", "l_hip_yaw", "l_knee", "l_ankle_pitch", "l_ankle_roll",
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0,              # right leg: "r_hip_roll", "r_hip_pitch", "r_hip_yaw", "r_knee", "r_ankle_pitch", "r_ankle_roll"
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,         # left arm:  "l_shoulder_pitch", "l_shoulder_roll", "l_shoulder_yaw", "l_elbow", "l_wrist_yaw", "l_wrist_pitch", "l_wrist_roll",
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,         # right arm: "r_shoulder_pitch", "r_shoulder_roll", "r_shoulder_yaw", "r_elbow", "r_wrist_yaw", "r_wrist_pitch", "r_wrist_roll"
    0.0, 0.0, 0.0, 0.0                         # head and waist: "head_roll", "head_pitch", "head_yaw", "waist_yaw"
    ]

ct_scale: [
          2.1, 2.1, 3.207, 2.673, 2.6, 2.6,         # left leg:  "l_hip_roll", "l_hip_pitch", "l_hip_yaw", "l_knee", "l_ankle_pitch", "l_ankle_roll",
          2.1, 2.1, 3.207, 2.673, 2.6, 2.6,         # right leg: "r_hip_roll", "r_hip_pitch", "r_hip_yaw", "r_knee", "r_ankle_pitch", "r_ankle_roll"
          3.207, 2.28, 5.89, 5.89, 3.35, 2.3, 2.3,  # left arm:  "l_shoulder_pitch", "l_shoulder_roll", "l_shoulder_yaw", "l_elbow", "l_wrist_yaw", "l_wrist_pitch", "l_wrist_roll",
          3.207, 2.28, 5.89, 5.89, 3.35, 2.3, 2.3,  # right arm: "r_shoulder_pitch", "r_shoulder_roll", "r_shoulder_yaw", "r_elbow", "r_wrist_yaw", "r_wrist_pitch", "r_wrist_roll"
          3.207, 3.207, 3.207, 3.207                # head and waist: "head_roll", "head_pitch", "head_yaw", "waist_yaw"
    ]


joint_kp_p: 
  [
    700.0, 700.0, 500.0, 700.0, 15.0, 15.0,   # left leg:  "l_hip_roll", "l_hip_pitch", "l_hip_yaw", "l_knee", "l_ankle_pitch", "l_ankle_roll",
    700.0, 700.0, 500.0, 700.0, 15.0, 15.0,   # right leg: "r_hip_roll", "r_hip_pitch", "r_hip_yaw", "r_knee", "r_ankle_pitch", "r_ankle_roll"
    60.0, 20.0, 10.0, 10.0, 10.0, 10.0, 10.0, # left arm:  "l_shoulder_pitch", "l_shoulder_roll", "l_shoulder_yaw", "l_elbow", "l_wrist_yaw", "l_wrist_pitch", "l_wrist_roll",
    60.0, 20.0, 10.0, 10.0, 10.0, 10.0, 10.0, # right arm: "r_shoulder_pitch", "r_shoulder_roll", "r_shoulder_yaw", "r_elbow", "r_wrist_yaw", "r_wrist_pitch", "r_wrist_roll"
    10.0, 5.0, 5.0, 5.0                       # head and waist: "head_roll", "head_pitch", "head_yaw", "waist_yaw" 
  ]
joint_kd_p: 
  [
    20.0, 20.0, 15.0, 10.0, 1.25, 1.25,       # left leg:  "l_hip_roll", "l_hip_pitch", "l_hip_yaw", "l_knee", "l_ankle_pitch", "l_ankle_roll",
    20.0, 20.0, 15.0, 10.0, 1.25, 1.25,       # right leg: "r_hip_roll", "r_hip_pitch", "r_hip_yaw", "r_knee", "r_ankle_pitch", "r_ankle_roll"
    3.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0,        # left arm:  "l_shoulder_pitch", "l_shoulder_roll", "l_shoulder_yaw", "l_elbow", "l_wrist_yaw", "l_wrist_pitch", "l_wrist_roll",
    3.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0,        # right arm: "r_shoulder_pitch", "r_shoulder_roll", "r_shoulder_yaw", "r_elbow", "r_wrist_yaw", "r_wrist_pitch", "r_wrist_roll"
    2.5, 2.5, 2.5, 2.5                        # head and waist: "head_roll", "head_pitch", "head_yaw", "waist_yaw" 
  ]


joystick:
  forward_command_offset: 0.0
  lateral_command_offset: 0.0
  rotation_command_offset: 0.0

simulation: false # 是否在仿真环境下运行 (Whether to run in simulation environment)

mlp:
  path: /config/policy/policy
